"use client";

import { motion } from "motion/react";
import { FileText, Loader2, RotateCw, Terminal } from "lucide-react";

import { MarkdownView } from "@/components/shared/MarkdownView";
import type { AsyncState, ReportResult } from "@/lib/types";

export function ReportPanel({
  state,
  onRetry,
  model = "local model",
}: {
  state: AsyncState<ReportResult>;
  onRetry: () => void;
  model?: string;
}) {
  return (
    <div className="panel p-5">
      <div className="mb-4 flex items-center gap-2.5">
        <span className="grid h-8 w-8 place-items-center rounded-lg border border-line bg-surface-2 text-accent">
          <FileText className="h-4 w-4" />
        </span>
        <div>
          <p className="eyebrow">
            Generated by <span className="text-accent">{model}</span> · local
          </p>
          <h3 className="font-display text-lg font-semibold tracking-tight text-ink-strong">
            Clinical report
          </h3>
        </div>
      </div>

      {state.status === "idle" && (
        <p className="text-sm text-muted">The report will be generated after a scan is analyzed.</p>
      )}

      {state.status === "loading" && (
        <div className="space-y-4" aria-live="polite">
          <div className="flex items-center gap-2 text-sm text-primary">
            <Loader2 className="h-4 w-4 animate-spin" />
            Generating local Meditron report… this can take a while.
          </div>
          <div className="space-y-2.5">
            {[5, 4, 5, 3, 4].map((w, i) => (
              <div key={i} className="skeleton h-3" style={{ width: `${w * 18}%` }} />
            ))}
          </div>
        </div>
      )}

      {state.status === "unavailable" && (
        <div className="space-y-3">
          <p className="text-sm text-muted">
            The local LLM report is disabled because Ollama isn&apos;t reachable.
          </p>
          <div className="rounded-lg border border-line bg-surface-2 p-3">
            <p className="mb-2 flex items-center gap-2 text-xs font-medium text-ink-strong">
              <Terminal className="h-3.5 w-3.5" /> Enable it
            </p>
            <pre className="data overflow-x-auto text-xs text-muted">
{`ollama serve
ollama pull ${model}`}
            </pre>
          </div>
        </div>
      )}

      {state.status === "error" && (
        <div className="space-y-3">
          <p className="text-sm text-glioma">{state.message}</p>
          <button
            type="button"
            onClick={onRetry}
            className="inline-flex items-center gap-2 rounded-lg border border-line bg-surface-2 px-3 py-2 text-sm font-medium text-ink-strong transition-colors hover:border-primary"
          >
            <RotateCw className="h-4 w-4" /> Regenerate
          </button>
        </div>
      )}

      {state.status === "success" && (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 0.4 }}
        >
          <MarkdownView source={state.data.reportMarkdown} />
          <button
            type="button"
            onClick={onRetry}
            className="mt-4 inline-flex items-center gap-2 rounded-lg border border-line bg-surface-2 px-3 py-1.5 text-xs font-medium text-muted transition-colors hover:border-primary hover:text-ink-strong"
          >
            <RotateCw className="h-3.5 w-3.5" /> Regenerate
          </button>
        </motion.div>
      )}
    </div>
  );
}
